# Generated by Django 3.1.5 on 2021-01-12 16:03
import pdb
from django.db import migrations


def transfer_datas(apps, schema_editor):
    pdb.set_trace()
    pokemon = apps.get_model('pokemon_entities', 'Pokemon')
    pokemon_entites = apps.get_model('pokemon_entities', 'PokemonEntity')
    post_pokemon_entites = apps.get_model('pokemon_entities', 'PostPokemonEntity')
    for pokemon_entity in pokemon_entites.objects.all():
        post_pokemon_entites.objects.create(
            pokemon=pokemon.objects.get(title='Бульбазавр'),
            lat=pokemon_entity.lat,
            lon=pokemon_entity.lon
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_postpokemonentity'),
    ]

    operations = [
        migrations.RunPython(transfer_datas),
    ]
