# Generated by Django 3.1.5 on 2021-01-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20210112_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PokemonEntity',
        ),
    ]
