# Generated by Django 3.1.5 on 2021-01-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_delete_pokemonentity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostPokemonEntity',
            new_name='PokemonEntity',
        ),
    ]
