# Generated by Django 3.1.5 on 2021-01-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_auto_20210119_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(related_name='pokemons_by_type', to='pokemon_entities.PokemonElementType', verbose_name='Типы стихий'),
        ),
    ]
