# Generated by Django 3.1.5 on 2021-01-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0020_pokemonelementtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(blank=True, related_name='elements_types', to='pokemon_entities.PokemonElementType', verbose_name='силен против'),
        ),
    ]
